#!/usr/bin/env python3

# set server timezone in UTC before time module imported
__import__('os').environ['TZ'] = 'UTC'
import odoo
import subprocess
import platform

if __name__ == "__main__":
    # List custom addons using the correct path
    if platform.system() == 'Windows':
        subprocess.run(['dir', r'.\custom_addons'], shell=True)
    else:
        subprocess.run(['ls', './custom_addons'])
    odoo.cli.main()
