[options]
addons_path = C:\Users\skhaddou\Desktop\LearnProject\Odoo17\odoo17\odoo\addons,C:\Users\skhaddou\Desktop\LearnProject\Odoo17\odoo17\addons,C:\Users\skhaddou\Desktop\LearnProject\Odoo17\odoo17\odoo\custom_addons
db_user = odoo17_user
db_password = odoo17
admin_passwd = $pbkdf2-sha512$600000$pnQuxdibU0rJWes9J6S0Ng$VjWGIsLKOfwEMkznsPNmGWgEwd/pg63URML.NRMkah.isXKM0yNs0bjvgaqag3I2.Z1hjtd11n5S7W3Wrw7POQ

bin_path = C:\Program Files\wkhtmltopdf\bin
wkhtmltopdf = C:\Program Files\wkhtmltopdf\bin\wkhtmltopdf.exe